# Generated by Django 4.2.11 on 2024-03-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='is_archived',
            field=models.BooleanField(default=True),
        ),
    ]
