# Generated by Django 4.2.11 on 2024-03-09 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
